title: 3dkaarkhana
email: contact@3dkaarkhana.in
description: "Professional 3D printing and rapid prototyping services for startups, engineering, and creative projects."
baseurl: ""
url: "https://journey-ai-biz.github.io"
author:
  name: 3dkaarkhana
  email: contact@3dkaarkhana.in

markdown: kramdown
theme: minima

enabled_plugins:
  - jekyll-feed
  
google_analytics: "G-X2J1EC0TKK"

collections: {}

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
